const getTerrains = () => [{
        id: 'Deep Sea 4',
        defaultDescription: ' is out in the deep ocean with nothing for miles around',
        fillStyle: '#091052ff',
        materialSpawns: ['oil', 'saltwater', 'treasure'],
        materialSpawnChance : [0.1, 1, 0.005],
    },
    {
        id: 'Deep Sea 3',
        defaultDescription: ' is out in the deep ocean with nothing for miles around',
        fillStyle: '#0b1158ff',
        materialSpawns: ['oil', 'fish', 'saltwater', 'treasure'],
        materialSpawnChance : [0.05, 0.25, 1, 0.0025],
    },
    {
        id: 'Deep Sea 2',
        defaultDescription: ' is out in the deep ocean with nothing for miles around',
        fillStyle: '#0d125cff',
        materialSpawns: ['fish', 'saltwater', 'shrimp'],
        materialSpawnChance : [0.25, 1, 0.1],
    },
    {
        id: 'Deep Sea 1',
        defaultDescription: ' is out in the deep ocean with nothing for miles around',
        fillStyle: '#101361ff',
        materialSpawns: ['fish', 'saltwater', 'shrimp'],
        materialSpawnChance : [0.375, 1, 0.175],
    },
    {
        id: 'Sea 4',
        defaultDescription: ' is out on the open ocean, but land is in sight',
        fillStyle: '#101388ff',
        materialSpawns: ['fish', 'shrimp', 'saltwater'],
        materialSpawnChance : [0.375, 0.125, 1],
    },
    {
        id: 'Sea 3',
        defaultDescription: ' is out on the open ocean, but land is in sight',
        fillStyle: '#101393ff',
        materialSpawns: ['fish', 'shrimp', 'saltwater', 'algae'],
        materialSpawnChance : [0.375, 0.075, 1, 0.125],
    },
    {
        id: 'Sea 2',
        defaultDescription: ' is out on the open ocean, but land is in sight',
        fillStyle: '#101399ff',
        materialSpawns: ['fish', 'algae', 'saltwater'],
        materialSpawnChance : [0.375, 0.175, 1],
    },
    {
        id: 'Sea 1',
        defaultDescription: ' is out on the open ocean, but land is in sight',
        fillStyle: '#1013a3ff',
        materialSpawns: ['fish', 'algae', 'saltwater'],
        materialSpawnChance : [0.425, 0.25, 1],
    },
    {
        id: 'Shallows 2',
        defaultDescription: ' is in the shallows',
        fillStyle: '#5754e8ff',
        materialSpawns: ['fish', 'algae', 'oysters', 'saltwater'],
        materialSpawnChance : [0.2, 0.375, 0.05, 1],
    },
    {
        id: 'Shallows 1',
        defaultDescription: ' is in the shallows',
        fillStyle: '#6974f4ff',
        materialSpawns: ['clams', 'clay', 'saltwater', 'shells', 'crabs'],
        materialSpawnChance : [0.25, 0.125, 1, 0.125, 0.024],
    },
    {
        id: 'Sand 1',
        defaultDescription: ' is on a beach, right near the water',
        fillStyle: '#ffffbaff',
        materialSpawns: ['deadwood', 'shells', 'crabs'],
        materialSpawnChance : [0.25, 0.125, 0.01],
    },
    {
        id: 'Sand 2',
        defaultDescription: ' is on a beach, not too far from the water',
        fillStyle: '#fff28fff',
        materialSpawns: ['deadwood', 'crabs'],
        materialSpawnChance : [0.25, 0.01],
    },
    {
        id: 'Sand 3',
        defaultDescription: ' is out in the dunes. The sea is not in sight, but waves can be heard nearby',
        fillStyle: '#f0ed6fff',
        materialSpawns: ['gravel', 'deadwood', 'plums'],
        materialSpawnChance : [0.1, 0.325, 0.05],
    },
    {
        id: 'Marsh 1',
        defaultDescription: ' is in a brackish, muddy marsh',
        fillStyle: '#98af4aff',
        materialSpawns: ['mud', 'clay', 'deadwood', 'saltwater', 'freshwater', 'plums'],
        materialSpawnChance : [0.75, 0.125, 0.25, 0.5, 0.0125, 0.0125],
    },
    {
        id: 'Marsh 2',
        defaultDescription: ' is in a brackish, dense, and muddy marsh',
        fillStyle: '#8a943aff',
        materialSpawns: ['mud', 'clay', 'methane', 'skunkweed', 'freshwater', 'deadwood'],
        materialSpawnChance : [0.75, 0.125, 0.075, 0.1, 0.0125, 0.25],
    },
    {
        id: 'Marsh 3',
        defaultDescription: ' is in a brackish, muddy marsh, with the edge of a field in sight',
        fillStyle: '#82893aff',
        materialSpawns: ['mud', 'clay', 'methane', 'mushrooms', 'freshwater', 'deadwood'],
        materialSpawnChance : [0.75, 0.125, 0.075, 0.1, 0.0125],
    },
    {
        id: 'Lower Grassland 1',
        defaultDescription: ' is in a pleasant field at the edge of a marsh',
        fillStyle: '#54b64cff',
        materialSpawns: ['flowers', 'berries', 'honeybees', 'deadwood', 'apples'],
        materialSpawnChance : [0.25, 0.125, 0.25, 0.1, 0.05],
    },
    {
        id: 'Lower Grassland 2',
        defaultDescription: ' is in a pleasant grassland, with the sun shining',
        fillStyle: '#54a446ff',
        materialSpawns: ['flowers', 'berries', 'honeybees'],
        materialSpawnChance : [0.25, 0.1, 0.25],
    },
    {
        id: 'Lower Grassland 3',
        defaultDescription: ' is in a pleasant grassland, with a forest in sight nearby',
        fillStyle: '#499a40ff',
        materialSpawns: ['flowers', 'berries', 'honeybees'],
        materialSpawnChance : [0.25, 0.05, 0.125],
    },
    {
        id: 'Forest 1',
        defaultDescription: ' is just inside a pleasant wood, with a nearby grassland easily accessible',
        fillStyle: '#3a8928ff',
        materialSpawns: ['wood', 'loam', 'berries', 'saplings', 'deadwood', 'mushrooms'],
        materialSpawnChance : [0.625, 0.5, 0.2, 0.2, 0.2, 0.1],
    },
    {
        id: 'Forest 2',
        defaultDescription: ' is in the interior of a pleasant wood, with sunlight shining through the canopy',
        fillStyle: '#337a25ff',
        materialSpawns: ['wood', 'loam', 'mushrooms', 'berries', 'vines', 'saplings', 'deadwood'],
        materialSpawnChance : [0.625, 0.5, 0.1, 0.2, 0.2, 0.2, 0.1],
    },
    {
        id: 'Forest 3',
        defaultDescription: ' is in the interior of a forest, with some light shining through the canopy',
        fillStyle: '#206a20ff',
        materialSpawns: ['wood', 'loam', 'mushrooms', 'berries', 'vines', 'deadwood'],
        materialSpawnChance : [0.625, 0.5, 0.1, 0.325, 0.25, 0.25],
    },
    {
        id: 'Forest 4',
        defaultDescription: ' is in the interior of a dark, dense forest',
        fillStyle: '#175a1cff',
        materialSpawns: ['wood', 'loam', 'mushrooms', 'berries', 'vines', 'deadwood'],
        materialSpawnChance : [0.625, 0.5, 0.1, 0.25, 0.25, 0.25],
    },
    {
        id: 'Forest 5',
        defaultDescription: ' is in the interior of a dark, dense forest',
        fillStyle: '#175a2cff',
        materialSpawns: ['wood', 'loam', 'mushrooms', 'berries', 'vines', 'deadwood'],
        materialSpawnChance : [0.625, 0.5, 0.1, 0.25, 0.25, 0.25],
    },
    {
        id: 'Forest 6',
        defaultDescription: ' is in the interior of a dark forest, with some grassland in sight',
        fillStyle: '#105832ff',
        materialSpawns: ['wood', 'loam', 'mushrooms', 'berries', 'vines', 'saplings', 'deadwood', 'apples'],
        materialSpawnChance : [0.625, 0.5, 0.1, 0.25, 0.25, 0.125, 0.25, 0.05],
    },
    {
        id: 'Upper Grassland 1',
        defaultDescription: ' is in some cool grassland with low-standing shrubs',
        fillStyle: '#5af875ff',
        materialSpawns: ['flowers', 'berries', 'honeybees'],
        materialSpawnChance : [0.25, 0.0125, 0.125],
    },
    {
        id: 'Upper Grassland 2',
        defaultDescription: ' is in some cool grassland with low-standing shrubs',
        fillStyle: '#5ad877ff',
        materialSpawns: ['flowers', 'berries'],
        materialSpawnChance : [0.25, 0.0125],
    },
    {
        id: 'Upper Grassland 3',
        defaultDescription: ' is in some cool grassland with patches of rock',
        fillStyle: '#55c785ff',
        materialSpawns: ['flowers', 'gravel', 'moss'],
        materialSpawnChance : [0.125, 0.325, 0.1],
    },
    {
        id: 'Bare Rock 1',
        defaultDescription: ' is on a bare rock face',
        fillStyle: '#999999ff',
        materialSpawns: ['gravel', 'quartz', 'ore', 'shale', 'moss'],
        materialSpawnChance : [0.325, 0.005, 0.0125, 0.1, 0.1],
    },
    {
        id: 'Bare Rock 2',
        defaultDescription: ' is on a bare rock face',
        fillStyle: '#a8a8a8ff',
        materialSpawns: ['gravel', 'quartz', 'ore', 'shale'],
        materialSpawnChance : [0.325, 0.005, 0.0125, 0.1],
    },
    {
        id: 'Bare Rock 3',
        defaultDescription: ' is on a bare rock face',
        fillStyle: '#bcbcbcff',
        materialSpawns: ['gravel', 'ore', 'shale', 'springwater'],
        materialSpawnChance : [0.325, 0.0125, 0.1, 0.005],
    },
    {
        id: 'Bare Rock 4',
        defaultDescription: ' is on a bare rock face near the summit of a mountain',
        fillStyle: '#c8c8c8ff',
        materialSpawns: ['gravel', 'ore', 'shale', 'gems', 'springwater'],
        materialSpawnChance : [0.325, 0.0125, 0.1, 0.0025, 0.005],
    },
    {
        id: 'Summit',
        defaultDescription: ' is at the top of a mountain. Everything for miles around can be seen',
        fillStyle: '#ddddddff',
        materialSpawns: ['gems', 'snow', 'springwater'],
        materialSpawnChance : [0.00625, 0.1, 0.01],
    },
]